// src/js/constants/action-types.js

export const SET_ROOT_CONTAINER = 'SET_ROOT_CONTAINER';

export const SET_SELECT_OVERLAY = 'SET_SELECT_OVERLAY';
export const SET_SELECT_OVERLAY_ENABLED = 'SET_SELECT_OVERLAY_ENABLED';
export const SET_SELECT_OVERLAY_POSITION = 'SET_SELECT_OVERLAY_POSITION';
export const SET_SELECT_OVERLAY_DIMENSIONS = 'SET_SELECT_OVERLAY_DIMENSIONS';

export const ADD_VERTEX = 'ADD_VERTEX';
export const INSERT_VERTEX_AFTER = 'INSERT_VERTEX_AFTER';
export const DELETE_VERTEX = 'DELETE_VERTEX';
export const MOVE_VERTEX = 'MOVE_VERTEX';
export const START_MOVE_VERTEX = 'START_MOVE_VERTEX';
export const STOP_MOVE_VERTEX = 'STOP_MOVE_VERTEX';
export const MOVE_VERTICES = 'MOVE_VERTICES';
export const SET_VERTEX_POSITIONS_RELATIVE_TO_COORDINATES =
  'SET_VERTEX_POSITIONS_RELATIVE_TO_COORDINATES';

export const CLOSE_SHAPE = 'CLOSE_SHAPE';
export const OPEN_SHAPE = 'OPEN_SHAPE';

export const SET_INTERACTION = 'SET_INTERACTION';
export const SET_MODE = 'SET_MODE';
export const SET_TOOL = 'SET_TOOL';

export const RESIZE = 'RESIZE';
export const SCALE_UI = 'SCALE_UI';

export const SET_BACKGROUND_COLOR = 'SET_BACKGROUND_COLOR';

export const SET_ALT_PRESSED = 'SET_ALT_PRESSED';
export const SET_CTRL_PRESSED = 'SET_CTRL_PRESSED';
export const SET_SHIFT_PRESSED = 'SET_SHIFT_PRESSED';

export const ADD_TEXTURE_SOURCE = 'ADD_TEXTURE_SOURCE';
export const REMOVE_TEXTURE_SOURCE = 'REMOVE_TEXTURE_SOURCE';

export const ADD_SPRITE = 'ADD_SPRITE';

export const CLEAR_PRESSED_KEYS = 'CLEAR_PRESSED_KEYS';
export const PRESS_KEY = 'PRESS_KEY';
export const RELEASE_KEY = 'RELEASE_KEY';
export const SET_ADD_KEY_PRESSED = 'SET_ADD_KEY_PRESSED';
export const SET_SUBTRACT_KEY_PRESSED = 'SET_SUBTRACT_KEY_PRESSED';
export const SET_PAN_KEY_PRESSED = 'SET_PAN_KEY_PRESSED';
