// src/js/constants/action-types.js

export const ADD_VERTEX = 'ADD_VERTEX';
export const DELETE_VERTEX = 'DELETE_VERTEX';
export const MOVE_VERTEX = 'MOVE_VERTEX';
export const START_MOVE_VERTEX = 'START_MOVE_VERTEX';
export const STOP_MOVE_VERTEX = 'STOP_MOVE_VERTEX';

export const RESIZE = 'RESIZE';
export const SCALE_UI = 'SCALE_UI';

export const SET_BACKGROUND_COLOR = 'SET_BACKGROUND_COLOR';

export const SET_ALT_PRESSED = 'SET_ALT_PRESSED';
export const SET_CTRL_PRESSED = 'SET_CTRL_PRESSED';

export const ADD_TEXTURE_SOURCE = 'ADD_TEXTURE_SOURCE';
export const REMOVE_TEXTURE_SOURCE = 'REMOVE_TEXTURE_SOURCE';

export const ADD_SPRITE = 'ADD_SPRITE';

export const SET_TEST_CONTAINER_POSITION = 'SET_TEST_CONTAINER_POSITION';
